import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "ar" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
}

const translations = {
  ar: {
    // Navbar
    "nav.browse": "تصفح",
    "nav.products": "المنتجات",
    "nav.contact": "تواصل معنا",
    "nav.storeName": "معرض",
    "nav.storeNameHighlight": "الطباخ",
    "nav.signIn": "تسجيل الدخول",
    "nav.signOut": "تسجيل الخروج",
    "nav.profile": "الملف الشخصي",
    "nav.sell": "بيع",
    "nav.sellSubtitle": "بيع على معرض الطباخ",
    "nav.wishlist": "قائمة الأمنيات",
    "search.placeholder": "ابحث عن المنتجات...",
    "search.here": "ابحث هنا...",
    "nav.searchPlaceholder": "ابحث عن المنتجات...",
    "nav.viewWishlist": "عرض قائمة الأمنيات",
    "nav.viewProfile": "عرض الملف الشخصي",
    "nav.about": "من نحن",

    // Hero
    "hero.badge": "أكثر من 500+ منتج متوفر",
    "hero.title": "منزلك،",
    "hero.titleHighlight": "أرقى",
    "hero.description": "اكتشف أدوات منزلية مميزة وعصرية للمطبخ والتنظيف وديكور المنزل.",
    "hero.searchPlaceholder": "ابحث عن المنتجات...",
    "hero.search": "بحث",
    "hero.popular": "الأكثر بحثاً:",
    "hero.tag.mealPrep": "تحضير الوجبات",
    "hero.tag.organization": "التنظيم",
    "hero.tag.cleaningHacks": "حيل التنظيف",
    "hero.shopNow": "تسوق الآن",
    "hero.becomeSeller": "كن بائعاً",

    // Filters
    "filters.title": "الفلاتر",
    "filters.reset": "إعادة ضبط",
    "rating.up": "فأكثر",
    "filter.filters": "الفلاتر",
    "filter.sortBy": "ترتيب حسب",
    "filter.category": "الفئة",
    "filter.priceRange": "نطاق السعر",
    "filter.rating": "التقييم",
    "filter.allRatings": "جميع التقييمات",
    "filter.featured": "مميز",
    "filter.priceLowToHigh": "السعر: من الأقل للأعلى",
    "filter.priceHighToLow": "السعر: من الأعلى للأقل",
    "filter.newest": "الأحدث",

    // Products
    "products.title": "استكشف",
    "products.titleHighlight": "المنتجات",
    "products.subtitle": "اعثر على الأدوات المنزلية المثالية لمنزلك",
    "products.noResults": "لا توجد منتجات مطابقة لبحثك.",
    "products.featured": "مميز",
    "products.department": "القسم",
    "products.customerReview": "تقييمات العملاء",
    "products.viewDetails": "عرض التفاصيل",
    "products.addToCart": "أضف إلى السلة",
    "products.addedToCart": "تمت الإضافة للسلة",
    "products.removeFromWishlist": "إزالة من المفضلة",
    "products.addToWishlist": "إضافة للمفضلة",
    "products.downloads": "تحميل",

    // Categories
    "category.all": "جميع المنتجات",
    "category.kitchen-tools": "أدوات المطبخ",
    "category.home-decor": "ديكور المنزل",
    "category.cleaning-supplies": "مستلزمات التنظيف",

    // Subcategories
    "subcategory.water-bottles": "زجاجات المياه",
    "subcategory.spoons": "ملاعق",
    "subcategory.forks": "شوكات",
    "subcategory.knives": "سكاكين",
    "subcategory.cutlery-sets": "أطقم أدوات المائدة",
    "subcategory.lunch-boxes": "صناديق الغداء",
    "subcategory.blenders": "خلاطات",
    "subcategory.hand-blenders": "خلاطات يدوية",

    // Specific Product Translations (matching IDs in products.ts)
    "product.1.name": "طقم مطبخ احترافي",
    "product.1.description": "أدوات مطبخ عالية الجودة من الفولاذ المقاوم للصدأ للطهي اليومي.",
    "product.2.name": "زجاجة مياه معزولة",
    "product.2.description": "حافظ على برودة مشروباتك لمدة 24 ساعة مع زجاجة المياه المتميزة لدينا.",
    "product.3.name": "خلاط طعام ذكي",
    "product.3.description": "خلاط عالي السرعة مع إعدادات مسبقة متعددة للعصائر والشوربات.",
    "product.4.name": "ساعة حائط كلاسيكية",
    "product.4.description": "ساعة حائط خشبية أنيقة لديكور المنزل العصري.",
    "product.5.name": "طقم تنظيف صديق للبيئة",
    "product.5.description": "مجموعة كاملة من لوازم التنظيف غير السامة لمنزلك.",
    "product.6.name": "سكين شيف ممتاز",
    "product.6.description": "سكين من الفولاذ الياباني المشكل للقطع الدقيق.",

    // Cart
    "cart.title": "سلة التسوق",
    "cart.items": "الأصناف",
    "cart.empty": "سلة التسوق فارغة",
    "cart.startShopping": "ابدأ التسوق",
    "cart.total": "الإجمالي",
    "cart.reviewOrder": "راجع طلبك وقم بالدفع عندما تكون مستعداً.",
    "cart.checkout": "المتابعة لإتمام الشراء",
    "cart.itemAdded": "تمت إضافة المنتج للسلة",
    "cart.itemRemoved": "تمت إزالة المنتج من السلة",
    "cart.addedToCart": "تمت الإضافة للسلة",
    "cart.increasedQuantity": "تم زيادة الكمية لـ",
    "cart.addedToCartDesc": "تمت إضافته إلى سلتك",

    // Checkout
    "checkout.title": "إتمام الشراء",
    "checkout.details": "تفاصيل الطلب",
    "checkout.shipping": "عنوان الشحن",
    "checkout.payment": "طريقة الدفع",
    "checkout.orderSummary": "ملخص الطلب",
    "checkout.placeOrder": "تأكيد الطلب",
    "checkout.subtotal": "المجموع الفرعي",
    "checkout.shippingCost": "تكلفة الشحن",
    "checkout.free": "مجاني",
    "checkout.fullName": "الاسم الكامل",
    "checkout.fullNamePlaceholder": "أدخل اسمك الكامل",
    "checkout.emailPlaceholder": "بريدك الإلكتروني",
    "checkout.phone": "رقم الهاتف",
    "checkout.phonePlaceholder": "رقم هاتفك",
    "checkout.address": "العنوان",
    "checkout.addressPlaceholder": "عنوانك الكامل",
    "checkout.city": "المدينة",
    "checkout.cityPlaceholder": "مدينتك",
    "checkout.postalCode": "الرمز البريدي",
    "checkout.postalCodePlaceholder": "الرمز البريدي",
    "checkout.country": "الدولة",
    "checkout.countryPlaceholder": "دولتك",
    "checkout.cardNumber": "رقم البطاقة",
    "checkout.cardNumberPlaceholder": "1234 5678 9012 3456",
    "checkout.expiryDate": "تاريخ الانتهاء",
    "checkout.expiryDatePlaceholder": "MM/YY",
    "checkout.cvv": "CVV",
    "checkout.cvvPlaceholder": "123",
    "checkout.orderSuccess": "تم تأكيد طلبك!",
    "checkout.orderSuccessDesc": "شكراً لك على طلبك. سنرسل لك تأكيداً عبر البريد الإلكتروني قريباً.",
    "checkout.continueShopping": "متابعة التسوق",

    // Creator Spotlight
    "creator.title": "أضواء على",
    "creator.titleHighlight": "المبدعين",
    "creator.subtitle": "تعرف على الخبراء وراء منتجاتنا الأكثر مبيعاً",
    "creator.products": "منتج",
    "creator.sales": "مبيعات",
    "creator.viewProfile": "عرض الملف",
    "creator.1.name": "أساسيات الشيف",
    "creator.1.bio": "أدوات مطبخ متميزة للمنازل العصرية",
    "creator.2.name": "ديزاين كو",
    "creator.2.bio": "متخصصون في ديكور المنزل البسيط",
    "creator.3.name": "جرين بيور",
    "creator.3.bio": "حلول تنظيف مستدامة",

    // Footer
    "footer.description": "وجهتك للأدوات المنزلية المميزة والعصرية.",
    "footer.marketplace": "المتجر",
    "footer.browseProducts": "تصفح المنتجات",
    "footer.categories": "الفئات",
    "footer.featured": "المميزة",
    "footer.newArrivals": "وصل حديثاً",
    "footer.bestSellers": "الأكثر مبيعاً",
    "footer.support": "الدعم",
    "footer.helpCenter": "مركز المساعدة",
    "footer.contactUs": "اتصل بنا",
    "footer.faqs": "الأسئلة الشائعة",
    "footer.refundPolicy": "سياسة الاسترجاع",
    "footer.terms": "شروط الخدمة",
    "footer.privacy": "سياسة الخصوصية",
    "footer.stayUpdated": "ابقَ على اطلاع",
    "footer.newsletter": "احصل على أحدث المنتجات والعروض الحصرية.",
    "footer.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "footer.copyright": "© 2024 معرض الطباخ. جميع الحقوق محفوظة.",
    "footer.cookies": "ملفات تعريف الارتباط",
    "footer.twitter": "تويتر",
    "footer.instagram": "انستقرام",
    "footer.youtube": "يوتيوب",
    "footer.whatsapp": "دردشة واتساب",
    "footer.subscribe": "اشتراك",

    // Auth
    "auth.backToHome": "العودة للرئيسية",
    "auth.welcomeBack": "مرحباً بعودتك",
    "auth.createAccount": "إنشاء حساب",
    "auth.signInSubtitle": "سجل الدخول للوصول إلى مشترياتك",
    "auth.signUpSubtitle": "سجل للبدء بالتسوق",
    "auth.displayName": "الاسم",
    "auth.displayNamePlaceholder": "اسمك",
    "auth.email": "البريد الإلكتروني",
    "auth.emailPlaceholder": "example@email.com",
    "auth.password": "كلمة المرور",
    "auth.passwordPlaceholder": "••••••••",
    "auth.signingIn": "جاري تسجيل الدخول...",
    "auth.creatingAccount": "جاري إنشاء الحساب...",
    "auth.signIn": "تسجيل الدخول",
    "auth.noAccount": "ليس لديك حساب؟ سجل الآن",
    "auth.hasAccount": "لديك حساب بالفعل؟ سجل الدخول",
    "auth.loginFailed": "فشل تسجيل الدخول",
    "auth.invalidCredentials": "بريد إلكتروني أو كلمة مرور غير صحيحة.",
    "auth.signUpFailed": "فشل إنشاء الحساب",
    "auth.accountExists": "يوجد حساب بهذا البريد. يرجى تسجيل الدخول.",
    "auth.welcomeBackToast": "مرحباً بعودتك!",
    "auth.successLogin": "تم تسجيل الدخول بنجاح.",
    "auth.accountCreated": "تم إنشاء الحساب!",
    "auth.welcomeToStore": "مرحباً بك في معرض الطباخ!",

    // Profile
    "profile.title": "ملفي الشخصي",
    "profile.subtitle": "إدارة ملفك الشخصي ومشاهدة مشترياتك",
    "profile.purchases": "مشترياتي",
    "profile.noPurchases": "لا توجد مشتريات بعد.",
    "profile.noPurchasesDesc": "ابدأ باستكشاف منتجاتنا!",
    "profile.edit": "تعديل الملف الشخصي",
    "profile.logout": "تسجيل الخروج",
    "profile.dashboard": "لوحة التحكم",
    "profile.myProducts": "منتجاتي",
    "profile.addProducts": "إضافة منتجات",
    "profile.myOrders": "طلباتي",
    "profile.settings": "الإعدادات",
    "profile.deleteAccount": "حذف الحساب",
    "profile.confirmDelete": "هل أنت متأكد أنك تريد حذف حسابك؟",
    "profile.deleteSuccess": "تم حذف الحساب بنجاح.",
    "profile.deleteError": "حدث خطأ أثناء حذف الحساب.",
    "profile.purchasedOn": "تم الشراء في",
    "profile.profileSettings": "إعدادات الملف الشخصي",
    "profile.emailNotice": "لا يمكن تغيير البريد الإلكتروني",
    "profile.updateError": "فشل تحديث الملف الشخصي.",
    "profile.saveSuccess": "تم حفظ التغييرات بنجاح.",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.overview": "نظرة عامة",
    "dashboard.totalSales": "إجمالي المبيعات",
    "dashboard.totalProducts": "إجمالي المنتجات",
    "dashboard.pendingOrders": "الطلبات المعلقة",
    "dashboard.recentOrders": "الطلبات الأخيرة",
    "dashboard.viewAll": "عرض الكل",
    "dashboard.productName": "اسم المنتج",
    "dashboard.price": "السعر",
    "dashboard.stock": "المخزون",
    "dashboard.status": "الحالة",
    "dashboard.actions": "الإجراءات",
    "dashboard.edit": "تعديل",
    "dashboard.delete": "حذف",
    "dashboard.orderId": "رقم الطلب",
    "dashboard.customer": "العميل",
    "dashboard.date": "التاريخ",
    "dashboard.amount": "المبلغ",
    "dashboard.deliveryStatus": "حالة التسليم",
    "dashboard.delivered": "تم التوصيل",
    "dashboard.pending": "معلق",
    "dashboard.shipped": "تم الشحن",
    "dashboard.cancelled": "ملغى",
    "dashboard.noOrders": "لا توجد طلبات حتى الآن.",
    "dashboard.noProducts": "لا توجد منتجات حتى الآن.",
    "dashboard.addProduct": "إضافة منتج",
    "dashboard.productAdded": "تمت إضافة المنتج بنجاح.",
    "dashboard.productUpdated": "تم تحديث المنتج بنجاح.",
    "dashboard.productDeleted": "تم حذف المنتج بنجاح.",
    "dashboard.confirmDeleteProduct": "هل أنت متأكد أنك تريد حذف هذا المنتج؟",
    "dashboard.uploadImage": "تحميل صورة",
    "dashboard.productDescription": "وصف المنتج",
    "dashboard.category": "الفئة",
    "dashboard.subcategory": "الفئة الفرعية",
    "dashboard.quantity": "الكمية",
    "dashboard.save": "حفظ",
    "dashboard.cancel": "إلغاء",
    "dashboard.add": "إضافة",
    "dashboard.editProduct": "تعديل المنتج",
    "dashboard.newProduct": "منتج جديد",
    "dashboard.image": "صورة",
    "dashboard.rating": "التقييم",
    "dashboard.reviews": "المراجعات",
    "dashboard.sales": "المبيعات",
    "dashboard.revenue": "الإيرادات",
    "dashboard.customers": "العملاء",
    "dashboard.messages": "الرسائل",
    "dashboard.reports": "التقارير",
    "dashboard.settings": "الإعدادات",
    "dashboard.logout": "تسجيل الخروج",
    "dashboard.welcome": "مرحباً بك في لوحة التحكم!",
    "dashboard.sellerProfile": "ملف البائع",
    "dashboard.updateProfile": "تحديث الملف الشخصي",
    "dashboard.profileUpdated": "تم تحديث الملف الشخصي بنجاح.",
    "dashboard.profileError": "حدث خطأ أثناء تحديث الملف الشخصي.",
    "dashboard.sellerName": "اسم البائع",
    "dashboard.sellerBio": "نبذة عن البائع",
    "dashboard.sellerImage": "صورة البائع",
    "dashboard.sellerEmail": "بريد البائع الإلكتروني",
    "dashboard.sellerPhone": "هاتف البائع",
    "dashboard.sellerAddress": "عنوان البائع",
    "dashboard.sellerWebsite": "موقع البائع",
    "dashboard.sellerSocial": "روابط التواصل الاجتماعي",
    "dashboard.sellerBank": "تفاصيل البنك",
    "dashboard.sellerAccount": "رقم الحساب",
    "dashboard.sellerBankName": "اسم البنك",
    "dashboard.sellerSwift": "رمز سويفت",
    "dashboard.sellerIban": "رقم الآيبان",
    "dashboard.sellerTaxId": "الرقم الضريبي",
    "dashboard.sellerVat": "رقم ضريبة القيمة المضافة",
    "dashboard.sellerBusinessName": "اسم العمل",
    "dashboard.sellerBusinessAddress": "عنوان العمل",
    "dashboard.sellerBusinessPhone": "هاتف العمل",
    "dashboard.sellerBusinessEmail": "بريد العمل الإلكتروني",
    "dashboard.sellerBusinessWebsite": "موقع العمل",
    "dashboard.sellerBusinessDescription": "وصف العمل",
    "dashboard.sellerBusinessLogo": "شعار العمل",
    "dashboard.sellerBusinessCover": "صورة غلاف العمل",
    "dashboard.sellerBusinessSocial": "روابط التواصل الاجتماعي للعمل",
    "dashboard.sellerBusinessTaxId": "الرقم الضريبي للعمل",
    "dashboard.sellerBusinessVat": "رقم ضريبة القيمة المضافة للعمل",
    "dashboard.sellerBusinessBank": "تفاصيل البنك للعمل",
    "dashboard.sellerBusinessAccount": "رقم الحساب للعمل",
    "dashboard.sellerBusinessBankName": "اسم البنك للعمل",
    "dashboard.sellerBusinessSwift": "رمز سويفت للعمل",
    "dashboard.sellerBusinessIban": "رقم الآيبان للعمل",
    "dashboard.sellerBusinessContactPerson": "شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactPhone": "هاتف شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactEmail": "بريد شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactRole": "دور شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactAddress": "عنوان شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactWebsite": "موقع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSocial": "روابط التواصل الاجتماعي لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactTaxId": "الرقم الضريبي لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactVat": "رقم ضريبة القيمة المضافة لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactBank": "تفاصيل البنك لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactAccount": "رقم الحساب لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactBankName": "اسم البنك لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSwift": "رمز سويفت لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactIban": "رقم الآيبان لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactDescription": "وصف شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactLogo": "شعار شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactCover": "صورة غلاف شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactImage": "صورة شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactRating": "تقييم شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactReviews": "مراجعات شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSales": "مبيعات شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactRevenue": "إيرادات شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactCustomers": "عملاء شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactMessages": "رسائل شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactReports": "تقارير شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSettings": "إعدادات شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactLogout": "تسجيل الخروج لشخص الاتصال للعمل",
    "dashboard.sellerBusinessContactWelcome": "مرحباً بك في لوحة تحكم شخص الاتصال للعمل!",
    "dashboard.sellerBusinessContactSellerProfile": "ملف بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactUpdateProfile": "تحديث ملف شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactProfileUpdated": "تم تحديث ملف شخص الاتصال للعمل بنجاح.",
    "dashboard.sellerBusinessContactProfileError": "حدث خطأ أثناء تحديث ملف شخص الاتصال للعمل.",
    "dashboard.sellerBusinessContactSellerName": "اسم بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBio": "نبذة عن بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerImage": "صورة بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerEmail": "بريد بائع شخص الاتصال للعمل الإلكتروني",
    "dashboard.sellerBusinessContactSellerPhone": "هاتف بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerAddress": "عنوان بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerWebsite": "موقع بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerSocial": "روابط التواصل الاجتماعي لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBank": "تفاصيل البنك لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerAccount": "رقم الحساب لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBankName": "اسم البنك لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerSwift": "رمز سويفت لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerIban": "رقم الآيبان لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerTaxId": "الرقم الضريبي لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerVat": "رقم ضريبة القيمة المضافة لبائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessName": "اسم عمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessAddress": "عنوان عمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessPhone": "هاتف عمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessEmail": "بريد عمل بائع شخص الاتصال للعمل الإلكتروني",
    "dashboard.sellerBusinessContactSellerBusinessWebsite": "موقع عمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessDescription": "وصف عمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessLogo": "شعار عمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessCover": "صورة غلاف عمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessSocial": "روابط التواصل الاجتماعي لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessTaxId": "الرقم الضريبي لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessVat": "رقم ضريبة القيمة المضافة لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessBank": "تفاصيل البنك لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessAccount": "رقم الحساب لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessBankName": "اسم البنك لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessSwift": "رمز سويفت لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessIban": "رقم الآيبان لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactPerson": "شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactPhone": "هاتف شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactEmail": "بريد شخص الاتصال لعمل بائع شخص الاتصال للعمل الإلكتروني",
    "dashboard.sellerBusinessContactSellerBusinessContactRole": "دور شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactAddress": "عنوان شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactWebsite": "موقع شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactSocial": "روابط التواصل الاجتماعي لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactTaxId": "الرقم الضريبي لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactVat": "رقم ضريبة القيمة المضافة لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactBank": "تفاصيل البنك لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactAccount": "رقم الحساب لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactBankName": "اسم البنك لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactSwift": "رمز سويفت لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactIban": "رقم الآيبان لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactDescription": "وصف شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactLogo": "شعار شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactCover": "صورة غلاف شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactImage": "صورة شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactRating": "تقييم شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactReviews": "مراجعات شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactSales": "مبيعات شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactRevenue": "إيرادات شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactCustomers": "عملاء شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactMessages": "رسائل شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactReports": "تقارير شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactSettings": "إعدادات شخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactLogout": "تسجيل الخروج لشخص الاتصال لعمل بائع شخص الاتصال للعمل",
    "dashboard.sellerBusinessContactSellerBusinessContactWelcome": "مرحباً بك في لوحة تحكم شخص الاتصال لعمل بائع شخص الاتصال للعمل!",
    // Common
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.loading": "جاري التحميل...",
    "common.user": "مستخدم",
    "common.previous": "السابق",
    "common.next": "التالي",

    // Wishlist
    "wishlist.title": "قائمة الأمنيات",
    "wishlist.empty": "قائمة أمنياتك فارغة",
    "wishlist.emptyDesc": "ابدأ بإضافة المنتجات التي تعجبك!",
    "wishlist.addedToWishlist": "تمت الإضافة لقائمة الأمنيات",
    "wishlist.removedFromWishlist": "تمت الإزالة من قائمة الأمنيات",

    // NotFound
    "notFound.title": "عذراً! الصفحة غير موجودة",

    // Product Features
    "product.feature1": "تحميل رقمي فوري",
    "product.feature2": "صيغة PDF قابلة للطباعة",
    "product.feature3": "وصول مدى الحياة",
    "product.feature4": "تحديثات مجانية مضمنة",
    "product.whatsIncluded": "ما المتضمن:",
    "product.oneTimePurchase": "شراء لمرة واحدة",
    "product.secureCheckout": "دفع آمن بواسطة Stripe",

    "dir": "rtl",
    "language": "ar",

    // About Page
    "about.title": "من نحن",
    "about.description": "نحن نؤمن بأن كل منزل يستحق أن يكون مريحاً وجميلاً. مهمتنا هي توفير منتجات منزلية عالية الجودة تجعل حياتك اليومية أسهل وأكثر متعة.",
    "about.value1Title": "جودة عالية",
    "about.value1Desc": "نختار بعناية كل منتج لضمان أعلى معايير الجودة",
    "about.value2Title": "أسعار عادلة",
    "about.value2Desc": "أسعار تنافسية بدون المساومة على الجودة",
    "about.value3Title": "شحن سريع",
    "about.value3Desc": "توصيل سريع وآمن إلى باب منزلك",
    "about.value4Title": "رضا العملاء",
    "about.value4Desc": "رضاك هو أولويتنا القصوى",
    "about.storyTitle": "قصتنا",
    "about.storyPara1": "بدأت Cozy Corner Goods في عام 2020 برؤية بسيطة: جعل المنتجات المنزلية عالية الجودة متاحة للجميع. ما بدأ كمتجر صغير عبر الإنترنت نما ليصبح سوقاً موثوقاً به يخدم آلاف العملاء السعداء.",
    "about.storyPara2": "نحن نعمل مباشرة مع الحرفيين والمصنعين المحليين لنقدم لك منتجات فريدة وعملية تجعل منزلك أكثر راحة. كل منتج في مجموعتنا يتم اختياره بعناية لضمان أنه يلبي معايير الجودة الصارمة لدينا.",
    "about.storyPara3": "اليوم، نحن فخورون بأن نكون أكثر من مجرد متجر - نحن مجتمع من محبي المنزل الذين يشاركون شغفاً بالجودة والراحة والأناقة.",

    // Contact Page
    "contact.title": "تواصل معنا",
    "contact.subtitle": "لديك سؤال؟ نحن هنا للمساعدة!",
    "contact.email": "البريد الإلكتروني",
    "contact.phone": "الهاتف",
    "contact.address": "العنوان",
    "contact.name": "الاسم",
    "contact.namePlaceholder": "اسمك الكامل",
    "contact.emailPlaceholder": "بريدك الإلكتروني",
    "contact.subject": "الموضوع",
    "contact.subjectPlaceholder": "كيف يمكننا مساعدتك؟",
    "contact.message": "الرسالة",
    "contact.messagePlaceholder": "اكتب رسالتك هنا...",
    "contact.send": "إرسال الرسالة",
    "contact.successTitle": "تم إرسال الرسالة!",
    "contact.successDesc": "شكراً لتواصلك معنا. سنرد عليك قريباً.",
  },
  en: {
    // Navbar
    "nav.browse": "Browse",
    "nav.products": "Products",
    "nav.contact": "Contact Us",
    "nav.storeName": "Al-Tabbakh",
    "nav.storeNameHighlight": "Store",
    "nav.signIn": "Sign In",
    "nav.signOut": "Sign Out",
    "nav.profile": "Profile",
    "nav.sell": "Sell",
    "nav.sellSubtitle": "Sell on Cozy Corner",
    "nav.wishlist": "Wishlist",
    "search.placeholder": "Search for products...",
    "search.here": "Search here...",
    "nav.viewWishlist": "View Wishlist",
    "nav.viewProfile": "View Profile",

    // Hero
    "hero.badge": "Over 500+ products available",
    "hero.title": "Your Home,",
    "hero.titleHighlight": "Elevated",
    "hero.description": "Discover premium home tools, decorations, and cleaning supplies for a better lifestyle.",
    "hero.searchPlaceholder": "Search for products...",
    "hero.search": "Search",
    "hero.popular": "Popular:",
    "hero.tag.mealPrep": "Meal Prep",
    "hero.tag.organization": "Organization",
    "hero.tag.cleaningHacks": "Cleaning Hacks",
    "hero.shopNow": "Shop Now",
    "hero.becomeSeller": "Become a Seller",

    // Filters
    "filters.title": "Filters",
    "filters.reset": "Reset",
    "rating.up": "& Up",

    // Products
    "products.title": "Explore",
    "products.titleHighlight": "Products",
    "products.subtitle": "Find the perfect home resources for your needs",
    "products.noResults": "No products found matching your criteria.",
    "products.featured": "Featured",
    "products.department": "Department",
    "products.customerReview": "Customer Review",
    "products.viewDetails": "View Details",
    "products.addToCart": "Add to Cart",
    "products.addedToCart": "Added to Cart",
    "products.removeFromWishlist": "Remove from Wishlist",
    "products.addToWishlist": "Add to Wishlist",
    "products.downloads": "Downloads",

    // Categories
    "category.all": "All Products",
    "category.kitchen-tools": "Kitchen Tools",
    "category.home-decor": "Home Décor",
    "category.cleaning-supplies": "Cleaning Supplies",

    // Subcategories
    "subcategory.water-bottles": "Water Bottles",
    "subcategory.spoons": "Spoons",
    "subcategory.forks": "Forks",
    "subcategory.knives": "Knives",
    "subcategory.cutlery-sets": "Cutlery Sets",
    "subcategory.lunch-boxes": "Lunch Boxes",
    "subcategory.blenders": "Blenders",
    "subcategory.hand-blenders": "Hand Blenders",

    // Specific Product Translations
    "product.1.name": "Professional Kitchen Set",
    "product.1.description": "High-quality stainless steel kitchen tools for everyday cooking.",
    "product.2.name": "Insulated Water Bottle",
    "product.2.description": "Keep your drinks cold for 24 hours with our premium water bottle.",
    "product.3.name": "Smart Food Blender",
    "product.3.description": "High-speed blender with multiple presets for smoothies and soups.",
    "product.4.name": "Minimalist Wall Clock",
    "product.4.description": "Elegant wooden wall clock for modern home decor.",
    "product.5.name": "Eco Cleaning Kit",
    "product.5.description": "Complete set of non-toxic cleaning supplies for your home.",
    "product.6.name": "Premium Chef Knife",
    "product.6.description": "Forged Japanese steel knife for precise cutting.",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.items": "items",
    "cart.empty": "Your cart is empty",
    "cart.startShopping": "Start Shopping",
    "cart.total": "Total",
    "cart.reviewOrder": "Review your items and checkout when you're ready.",
    "cart.checkout": "Proceed to Checkout",
    "cart.itemAdded": "Item added to cart",
    "cart.itemRemoved": "Item removed from cart",

    // Checkout
    "checkout.title": "Checkout",
    "checkout.details": "Order Details",
    "checkout.shipping": "Shipping Address",
    "checkout.payment": "Payment Method",
    "checkout.orderSummary": "Order Summary",
    "checkout.placeOrder": "Place Order",
    "checkout.subtotal": "Subtotal",
    "checkout.shippingCost": "Shipping",
    "checkout.free": "Free",

    // Creator Spotlight
    "creator.title": "Creator",
    "creator.titleHighlight": "Spotlight",
    "creator.subtitle": "Meet the experts behind our best-selling products",
    "creator.products": "Products",
    "creator.sales": "Sales",
    "creator.viewProfile": "View Profile",
    "creator.1.name": "Chef Essentials",
    "creator.1.bio": "Premium kitchenware for modern homes",
    "creator.2.name": "DesignCo",
    "creator.2.bio": "Minimalist home decor specialists",
    "creator.3.name": "GreenPure",
    "creator.3.bio": "Sustainable cleaning solutions",

    // Footer
    "footer.description": "Your destination for premium home organization resources.",
    "footer.marketplace": "Marketplace",
    "footer.browseProducts": "Browse Products",
    "footer.categories": "Categories",
    "footer.featured": "Featured",
    "footer.newArrivals": "New Arrivals",
    "footer.bestSellers": "Best Sellers",
    "footer.support": "Support",
    "footer.helpCenter": "Help Center",
    "footer.contactUs": "Contact Us",
    "footer.faqs": "FAQs",
    "footer.refundPolicy": "Refund Policy",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.stayUpdated": "Stay Updated",
    "footer.newsletter": "Get the latest products and exclusive deals.",
    "footer.emailPlaceholder": "Enter your email",
    "footer.copyright": "© 2024 Al-Tabbakh Store. All rights reserved.",
    "footer.cookies": "Cookies",
    "footer.twitter": "Twitter",
    "footer.instagram": "Instagram",
    "footer.youtube": "YouTube",
    "footer.whatsapp": "Chat on WhatsApp",
    "footer.subscribe": "Subscribe",

    // Auth
    "auth.backToHome": "Back to Home",
    "auth.welcomeBack": "Welcome back",
    "auth.createAccount": "Create account",
    "auth.signInSubtitle": "Sign in to access your purchases",
    "auth.signUpSubtitle": "Sign up to start shopping",
    "auth.displayName": "Display Name",
    "auth.displayNamePlaceholder": "Your name",
    "auth.email": "Email",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "••••••••",
    "auth.signingIn": "Signing in...",
    "auth.creatingAccount": "Creating account...",
    "auth.signIn": "Sign In",
    "auth.noAccount": "Don't have an account? Sign up",
    "auth.hasAccount": "Already have an account? Sign in",
    "auth.loginFailed": "Login failed",
    "auth.invalidCredentials": "Invalid email or password. Please try again.",
    "auth.signUpFailed": "Sign up failed",
    "auth.accountExists": "An account with this email already exists. Please sign in instead.",
    "auth.welcomeBackToast": "Welcome back!",
    "auth.successLogin": "You have successfully logged in.",
    "auth.accountCreated": "Account created!",
    "auth.welcomeToStore": "Welcome to Al-Tabbakh Store!",

    // Profile
    "profile.title": "My Profile",
    "profile.subtitle": "Manage your profile and view your purchases",
    "profile.purchases": "My Purchases",
    "profile.noPurchases": "No purchases yet.",
    "profile.noPurchasesDesc": "Start exploring our products!",
    "profile.edit": "Edit Profile",
    "profile.logout": "Logout",
    "profile.dashboard": "Dashboard",
    "profile.myProducts": "My Products",
    "profile.addProducts": "Add Products",
    "profile.myOrders": "My Orders",
    "profile.settings": "Settings",
    "profile.deleteAccount": "Delete Account",
    "profile.confirmDelete": "Are you sure you want to delete your account?",
    "profile.deleteSuccess": "Account deleted successfully.",
    "profile.deleteError": "Error deleting account.",
    "profile.purchasedOn": "Purchased on",
    "profile.profileSettings": "Profile Settings",
    "profile.emailNotice": "Email cannot be changed",
    "profile.updateError": "Failed to update profile.",
    "profile.saveSuccess": "Changes saved successfully.",

    // Common
    "common.error": "Error",
    "common.success": "Success",
    "common.loading": "Loading...",
    "common.user": "User",
    "common.previous": "Previous",
    "common.next": "Next",

    // Wishlist
    "wishlist.title": "Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.emptyDesc": "Start adding products you love!",
    "wishlist.addedToWishlist": "Added to wishlist",
    "wishlist.removedFromWishlist": "Removed from wishlist",

    // NotFound
    "notFound.title": "Oops! Page not found",

    // Product Features
    "product.feature1": "Instant digital download",
    "product.feature2": "Printable PDF format",
    "product.feature3": "Lifetime access",
    "product.feature4": "Free updates included",
    "product.whatsIncluded": "What's included:",
    "product.oneTimePurchase": "One-time purchase",
    "product.secureCheckout": "Secure checkout powered by Stripe",

    // Search & Filters
    "nav.searchPlaceholder": "Search for products...",
    "nav.about": "About",
    "filter.filters": "Filters",
    "filter.sortBy": "Sort By",
    "filter.category": "Category",
    "filter.priceRange": "Price Range",
    "filter.rating": "Rating",
    "filter.allRatings": "All Ratings",
    "filter.featured": "Featured",
    "filter.priceLowToHigh": "Price: Low to High",
    "filter.priceHighToLow": "Price: High to Low",
    "filter.newest": "Newest",

    // About Page
    "about.title": "About Us",
    "about.description": "We believe every home deserves to be comfortable and beautiful. Our mission is to provide high-quality home products that make your daily life easier and more enjoyable.",
    "about.value1Title": "High Quality",
    "about.value1Desc": "We carefully select each product to ensure the highest quality standards",
    "about.value2Title": "Fair Prices",
    "about.value2Desc": "Competitive pricing without compromising on quality",
    "about.value3Title": "Fast Shipping",
    "about.value3Desc": "Quick and secure delivery to your doorstep",
    "about.value4Title": "Customer Satisfaction",
    "about.value4Desc": "Your satisfaction is our top priority",
    "about.storyTitle": "Our Story",
    "about.storyPara1": "Cozy Corner Goods started in 2020 with a simple vision: make high-quality home products accessible to everyone. What began as a small online store has grown into a trusted marketplace serving thousands of happy customers.",
    "about.storyPara2": "We work directly with local artisans and manufacturers to bring you unique, practical products that make your home more comfortable. Every product in our collection is carefully selected to ensure it meets our strict quality standards.",
    "about.storyPara3": "Today, we're proud to be more than just a store - we're a community of home enthusiasts who share a passion for quality, comfort, and elegance.",

    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "Have a question? We're here to help!",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your full name",
    "contact.emailPlaceholder": "Your email",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "How can we help you?",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Write your message here...",
    "contact.send": "Send Message",
    "contact.successTitle": "Message sent!",
    "contact.successDesc": "Thank you for contacting us. We'll get back to you soon.",

    "dir": "ltr",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "ar";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ar] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
