// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE flow returns auth codes as ?code= query params instead of
    // #access_token= hash fragments. This is critical because:
    // 1. HashRouter uses # for routing — hash tokens conflict
    // 2. Lovable's email tracker strips hash fragments from URLs
    // Query params survive both issues.
    flowType: 'pkce',
    // We handle the ?code= param manually in main.tsx before React mounts,
    // so disable Supabase's automatic URL detection.
    detectSessionInUrl: false,
  }
});